#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config top_padding 14

bspc config border_width        1
bspc config window_gap          10
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp floating=on

bash /home/glindste/.fehbg
/home/glindste/.config/bspwm/panel
