# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
alpha-nvim = "scm"
"ccc.nvim" = "1.6.0"
cmp-nvim-lsp = "scm"
"comment.nvim" = "0.8.0"
"headlines.nvim" = "4.0.1"
"hlchunk.nvim" = "1.0.1"
"kanagawa.nvim" = { version = "scm", opt = true }
"lspkind.nvim" = "scm"
"lspsaga.nvim" = "scm"
"lualine.nvim" = "scm"
luasnip = "2.2.0"
"mason-lspconfig.nvim" = "1.27.0"
"mason.nvim" = "1.10.0"
neorg = "8.2.0"
"neo-tree.nvim" = "3.14"
"noice.nvim" = "2.0.1"
nvim-cmp = "0.0.1"
nvim-lspconfig = "0.1.7"
nvim-notify = "3.13.4"
"rocks-config.nvim" = "1.2.3"
"rocks-git.nvim" = "1.3.0"
"rocks.nvim" = "2.19.1"
"rocks-treesitter.nvim" = "scm"
rustaceanvim = "4.18.0"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.10.0"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-vimdoc = "scm"
"trouble.nvim" = "2.10.0"
"which-key.nvim" = "1.6.0"
promise-async = "scm" # dep of nvim-ufo
"neodev.nvim" = "2.5.2"
"statuscol.nvim" = "scm"
"overseer.nvim" = "1.3.1"
neotest = "4.2.0"
nvim-dap-ui = "4.0.0"
"go.nvim" = "0.2.1"
"plenary.nvim" = "scm"

# https://github.com/nvim-neorg/neorg/issues/1351
[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

# not available on luarocks yet
[plugins.neorg-telescope]
git = "nvim-neorg/neorg-telescope"

# not available on luarocks yet
[plugins.lsp-format]
git = "lukas-reineke/lsp-format.nvim"

# not available on luarocks
[plugins.vim-visual-multi]
git = "mg979/vim-visual-multi"

# fails to install from luarocks
[plugins.gitsigns]
git = "lewis6991/gitsigns.nvim"

# not in luarocks yet
[plugins.barbar]
git = "romgrk/barbar.nvim"

# not in luarocks yet
[plugins.unimpaired]
git = "tummetott/unimpaired.nvim"
config = { options = {} }

# not in luarocks yet
[plugins.null-ls]
git = "nvimtools/none-ls.nvim"

# not in luarocks yet
[plugins.ufo]
git = "kevinhwang91/nvim-ufo"

# not in luarocks yet
[plugins.neotest-go]
git = "nvim-neotest/neotest-go"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[config]
plugins_dir = "rocks_plugins/"

[plugins.Comment.config]
options = {}

[plugins.headlines.config]
options = {}

[plugins.dapui.config]
options = {}

[plugins.go.config]
options = {}

[plugins.lualine.config.options]
extensions = ["neo-tree", "overseer", "nvim-dap-ui"]

[plugins.lspsaga.config]
options = { finder = { keys = { toggle_or_open = "<CR>" } }, lightbulb = { sign = "false" } }
