# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
# colorscheme = "kanagawa"
colorscheme = "eldritch"
plugins_dir = "rocks_plugins/"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
alpha-nvim = "scm"
"ccc.nvim" = "1.6.0"
"comment.nvim" = "0.8.0"
"go.nvim" = "scm"
"headlines.nvim" = "scm"
"hlchunk.nvim" = "1.1.0"
"kanagawa.nvim" = "scm"
"lspkind.nvim" = "scm"
"lspsaga.nvim" = "scm"
"lualine.nvim" = "scm"
luasnip = "2.3.0"
"mason-lspconfig.nvim" = "1.30.0"
"mason.nvim" = "1.10.0"
"neodev.nvim" = "3.0.0"
neorg = "9.1.1"
neorg-telescope = "1.2.2"
neotest = "5.4.1"
"neo-tree.nvim" = "3.26"
# https://github.com/neovim/neovim/issues/21056
# "noice.nvim" = "2.0.1"
"none-ls.nvim" = "scm"
nvim-dap-ui = "4.0.0"
nvim-lspconfig = "0.1.8"
nvim-notify = "3.13.5"
nvim-ufo = "1.4.0"
"overseer.nvim" = "1.4.0"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "2.2.0"
"rocks-dev.nvim" = "1.5.0"
"rocks-edit.nvim" = "scm"
"rocks-git.nvim" = "2.0.1"
"rocks.nvim" = "2.38.2"
"rocks-treesitter.nvim" = "1.0.3"
rustaceanvim = "5.2.2"
"statuscol.nvim" = "scm"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.12.0"
tree-sitter-bash = "0.0.2"
tree-sitter-go = "0.0.3"
tree-sitter-jsonc = "0.0.2"
tree-sitter-jsonnet = "0.0.4"
tree-sitter-json = "0.0.3"
tree-sitter-lua = "0.0.2"
tree-sitter-markdown = "0.0.2"
tree-sitter-proto = "0.0.2"
tree-sitter-python = "0.0.3"
tree-sitter-starlark = "0.0.2"
tree-sitter-toml = "0.0.2"
tree-sitter-vimdoc = "0.0.2"
tree-sitter-vim = "0.0.3"
"unimpaired.nvim" = "0.2.0"
"which-key.nvim" = "3.13.2"
# tree-sitter-just = "scm"
tree-sitter-gitignore = "0.0.2"
tree-sitter-make = "0.0.2"
tree-sitter-yaml = "0.0.2"
tree-sitter-query = "0.0.2"
tree-sitter-norg = "0.2.4"
tree-sitter-hcl = "0.0.2"
tree-sitter-dockerfile = "0.0.2"
cmp-nvim-lsp = "scm"
nvim-cmp= "scm"
tree-sitter-dot = "0.0.2"
tree-sitter-css = "0.0.3"
tree-sitter-xml = "0.0.2"
nvim-lint = "scm"
tree-sitter-fish = "0.0.2"
tree-sitter-javascript = "0.0.3"
tree-sitter-ini = "0.0.2"
tree-sitter-gomod = "0.0.3"
tree-sitter-gosum = "0.0.2"
tree-sitter-terraform = "0.0.2"

[plugins.vim-just]
git = "NoahTheDuke/vim-just"
rev = "3143de2ee5b784d99e5322fd3382823ce8eb845c"

[plugins.lsp-format]
git = "lukas-reineke/lsp-format.nvim"
rev = "v2.7.0"

[plugins.gitsigns]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.barbar]
git = "romgrk/barbar.nvim"
rev = "v1.9.1^{}"

[plugins.neotest-go]
git = "nvim-neotest/neotest-go"
rev = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6"

[plugins.eldritch]
git = "eldritch-theme/eldritch.nvim"
rev = "63268ea7135faa013840d07653181b008dbaacae"

[plugins.vim-visual-multi]
git = "mg979/vim-visual-multi"
rev = "v0.5.8^{}"

# # not available on luarocks
# [plugins.vim-just]
# git = "NoahTheDuke/vim-just"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[plugins.unimpaired.config]
options = {}

[plugins.Comment.config]
options = {}

[plugins.headlines.config]
options = {}

[plugins.dapui.config]
options = {}

[plugins.go.config]
options = {}
