# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
# colorscheme = "kanagawa"
colorscheme = "eldritch"
plugins_dir = "rocks_plugins/"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
alpha-nvim = "scm"
"ccc.nvim" = "2.0.3"
"comment.nvim" = "0.8.0"
"go.nvim" = "scm"
"headlines.nvim" = "scm"
"hlchunk.nvim" = "1.3.0"
"kanagawa.nvim" = "scm"
"lspkind.nvim" = "scm"
"lspsaga.nvim" = "scm"
"lualine.nvim" = "scm"
luasnip = "2.3.0"
"mason-lspconfig.nvim" = "1.31.0"
"mason.nvim" = "1.10.0"
"neodev.nvim" = "3.0.0"
neorg = "9.1.1"
neorg-telescope = "1.2.2"
neotest = "5.6.1"
"neo-tree.nvim" = "3.27"
# https://github.com/neovim/neovim/issues/21056
# "noice.nvim" = "2.0.1"
"none-ls.nvim" = "scm"
nvim-dap-ui = "4.0.0"
nvim-lspconfig = "1.2.0"
nvim-notify = "3.14.0"
nvim-ufo = "1.4.0"
"overseer.nvim" = "1.5.0"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "3.1.0"
"rocks-dev.nvim" = "1.7.0"
"rocks-edit.nvim" = "scm"
"rocks-git.nvim" = "2.5.2"
"rocks.nvim" = "2.43.0"
"rocks-treesitter.nvim" = "1.3.0"
rustaceanvim = "5.20.1"
"statuscol.nvim" = "scm"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.13.0"
tree-sitter-bash = "scm"
tree-sitter-go = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-jsonnet = "scm"
tree-sitter-json = "scm"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-proto = "scm"
tree-sitter-python = "scm"
tree-sitter-starlark = "scm"
tree-sitter-toml = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-vim = "scm"
"unimpaired.nvim" = "0.2.0"
"which-key.nvim" = "3.15.0"
# tree-sitter-just = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-make = "scm"
tree-sitter-yaml = "scm"
tree-sitter-query = "scm"
tree-sitter-hcl = "scm"
tree-sitter-dockerfile = "scm"
cmp-nvim-lsp = "scm"
nvim-cmp= "scm"
tree-sitter-dot = "scm"
tree-sitter-css = "scm"
tree-sitter-xml = "scm"
nvim-lint = "scm"
tree-sitter-fish = "scm"
tree-sitter-javascript = "scm"
tree-sitter-ini = "scm"
tree-sitter-gomod = "scm"
tree-sitter-gosum = "scm"
tree-sitter-terraform = "scm"
tree-sitter-cpp = "0.0.35"
tree-sitter-editorconfig = "0.0.45"

[plugins.vim-just]
git = "NoahTheDuke/vim-just"
rev = "fbe69d1723230e14f245ca34b0c98fa916b36f64"

[plugins.lsp-format]
git = "lukas-reineke/lsp-format.nvim"
rev = "v2.7.1"

[plugins.gitsigns]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.barbar]
git = "romgrk/barbar.nvim"
rev = "v1.9.1"

[plugins.neotest-go]
git = "nvim-neotest/neotest-go"
rev = "92950ad7be2ca02a41abca5c6600ff6ffaf5b5d6"

[plugins.eldritch]
git = "eldritch-theme/eldritch.nvim"
rev = "48788ef2f7be7e86b0a57ef87f1a96bc18e24b8b"

[plugins.vim-visual-multi]
git = "mg979/vim-visual-multi"
rev = "v0.5.8"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
disable = [
    "text"
]

[plugins.comment.config]
options = {}

[plugins.headlines.config]
options = {}

[plugins.dapui.config]
options = {}

[plugins.go.config]
options = {}
