# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
# colorscheme = "kanagawa"
colorscheme = "eldritch"
plugins_dir = "rocks_plugins/"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
alpha-nvim = "scm"
"ccc.nvim" = "1.6.0"
cmp-nvim-lsp = "scm"
"comment.nvim" = "0.8.0"
"go.nvim" = "0.2.1"
"headlines.nvim" = "scm"
"hlchunk.nvim" = "1.1.0"
"kanagawa.nvim" = "scm"
"lspkind.nvim" = "scm"
"lspsaga.nvim" = "scm"
"lualine.nvim" = "scm"
luasnip = "2.3.0"
"mason-lspconfig.nvim" = "1.29.0"
"mason.nvim" = "1.10.0"
"neodev.nvim" = "3.0.0"
neorg = "8.7.1"
neorg-telescope = "1.1.0"
neotest = "5.3.3"
"neo-tree.nvim" = "3.26"
# https://github.com/neovim/neovim/issues/21056
# "noice.nvim" = "2.0.1"
"none-ls.nvim" = "scm"
nvim-cmp = "0.0.1"
nvim-dap-ui = "4.0.0"
nvim-lspconfig = "0.1.8"
nvim-notify = "3.13.5"
nvim-ufo = "1.4.0"
"overseer.nvim" = "1.4.0"
"plenary.nvim" = "scm"
"rocks-config.nvim" = "2.0.0"
"rocks-dev.nvim" = "1.2.3"
"rocks-git.nvim" = "1.5.1"
"rocks.nvim" = "2.31.3"
"rocks-treesitter.nvim" = "scm"
rustaceanvim = "4.25.1"
"statuscol.nvim" = "scm"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.11.0"
tree-sitter-bash = "scm"
tree-sitter-go = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-jsonnet = "scm"
tree-sitter-json = "scm"
tree-sitter-lua = "scm"
tree-sitter-markdown = "scm"
tree-sitter-proto = "scm"
tree-sitter-python = "scm"
tree-sitter-starlark = "scm"
tree-sitter-toml = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-vim = "scm"
"unimpaired.nvim" = "0.2.0"
"which-key.nvim" = "2.1.0"
# tree-sitter-just = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-make = "scm"
tree-sitter-yaml = "scm"
tree-sitter-query = "scm"

[plugins.vim-just]
git = "NoahTheDuke/vim-just"

# https://github.com/nvim-neorg/neorg/issues/1351
# [plugins.nvim-treesitter]
# git = "nvim-treesitter/nvim-treesitter"
# rev = "v0.9.2^{}"

# not available on luarocks yet
[plugins.lsp-format]
git = "lukas-reineke/lsp-format.nvim"

# fails to install from luarocks
[plugins.gitsigns]
git = "lewis6991/gitsigns.nvim"

# not in luarocks yet
[plugins.barbar]
git = "romgrk/barbar.nvim"

# not in luarocks yet
[plugins.neotest-go]
git = "nvim-neotest/neotest-go"

[plugins.eldritch]
git = "eldritch-theme/eldritch.nvim"

# not available on luarocks, y tho? PR got merged
[plugins.vim-visual-multi]
git = "mg979/vim-visual-multi"

# # not available on luarocks
# [plugins.vim-just]
# git = "NoahTheDuke/vim-just"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[plugins.unimpaired.config]
options = {}

[plugins.Comment.config]
options = {}

[plugins.headlines.config]
options = {}

[plugins.dapui.config]
options = {}

[plugins.go.config]
options = {}

[plugins.lspsaga.config]
options = { finder = { keys = { toggle_or_open = "<CR>" } }, lightbulb = { sign = "false" } }
